"""directionsaddedtobooking

Revision ID: 0b6908dcf800
Revises: f3ab061c67b9
Create Date: 2024-07-14 14:06:42.050511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b6908dcf800'
down_revision = 'f3ab061c67b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directions_data', mysql.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('directions_data')

    # ### end Alembic commands ###
