"""cancelled_ride_added

Revision ID: f3ab061c67b9
Revises: 7eee59a72f0f
Create Date: 2024-07-14 13:39:32.867774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ab061c67b9'
down_revision = '7eee59a72f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancelled_ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancelled_ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
