"""bookingdetailsadded

Revision ID: fdbc20444305
Revises: 9c774871f9c0
Create Date: 2024-07-15 22:39:11.417747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdbc20444305'
down_revision = '9c774871f9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookingdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_latitude', sa.String(length=200), nullable=True),
    sa.Column('user_longitude', sa.String(length=200), nullable=True),
    sa.Column('directions_data', mysql.JSON(), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('directions_data')
        batch_op.drop_column('distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('directions_data', mysql.JSON(), nullable=False))

    op.drop_table('bookingdetails')
    # ### end Alembic commands ###
